
/*  This file is automatically generated by bitmapgen.py
*/
#include <stdint.h>
#include "osdpainter.h"

extern OsdBitmap bitmapdracologo;
extern OsdBitmap bitmapsatelite;
extern OsdBitmap bitmapbattery;
extern OsdBitmap bitmapclock;
extern OsdBitmap bitmapmode;


const OsdBitmap* const osdBitmapsList[] = {&bitmapdracologo, &bitmapsatelite, &bitmapbattery, &bitmapclock, &bitmapmode, 0};

