
/*  This file is automatically generated by fontgen.py
*/
#include <stdint.h>
#include "osdpainter.h"

extern OsdFont fontconsolas10;
extern OsdFont fontconsolas12;
extern OsdFont fontconsolas14;
extern OsdFont fontconsolas16;
extern OsdFont fontconsolas18;


const OsdFont* const osdFontsList[] = {&fontconsolas10, &fontconsolas12, &fontconsolas14, &fontconsolas16, &fontconsolas18, 0};

